plugins {
    id "net.neoforged.moddev" version "2.0.147"
}

java {
    toolchain.languageVersion = JavaLanguageVersion.of(25)
}

dependencies {
    implementation project(":common")

    jarJar("org.yaml:snakeyaml:2.7")
}

neoForge {
    version = "26.2.0.52-beta"
    validateAccessTransformers = true

    mods {
        testproject {
            sourceSet sourceSets.main
        }
    }
}
